name: Push Events
on:
  workflow_dispatch:
   inputs:
     param1:
      description: "Description for param1"
      required: true
      default: "Hello World"
jobs:
  show-info:
    runs-on: ubuntu-latest
    steps:
    - name: Run Manual Tasks
      run: |
        echo "Running manual task with Param1: ${{github.event.inputs.param1}}"
